version: "3.9"
services:
  php:
    build:
      context: ./api/docker/php
    container_name: app-php
    volumes:
      - ./api:/var/www/html
    environment:
      PHP_MEMORY_LIMIT: 512M
    depends_on:
      - db
      - redis

  nginx:
    image: nginx:1.27-alpine
    container_name: app-nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php

  db:
    image: postgres:16-alpine
    container_name: app-postgres
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: app-redis
    ports:
      - "6379:6379"

  dashboard:
    build:
      context: ./dashboard
    container_name: app-dashboard
    ports:
      - "5173:5173"
    environment:
      HOST: 0.0.0.0
    volumes:
      - ./dashboard:/app
      - /app/node_modules
    command: yarn dev --host 0.0.0.0 --port 5173

volumes:
  pgdata:
